import type { EngagementOverview } from '../types'

const nf = new Intl.NumberFormat(undefined, { maximumFractionDigits: 1 })
const ni = new Intl.NumberFormat(undefined, { maximumFractionDigits: 0 })

type Props = {
  overview: EngagementOverview
}

export function KpiCards({ overview }: Props) {
  const items: { label: string; value: string; hint: string }[] = [
    {
      label: 'Inbound messages',
      value: ni.format(overview.total_inbound_messages),
      hint: 'Messages users sent to the Twin',
    },
    {
      label: 'Outbound messages',
      value: ni.format(overview.total_outbound_messages),
      hint: 'Replies generated by the Twin',
    },
    {
      label: 'New conversations',
      value: ni.format(overview.total_conversations),
      hint: 'Threads started in the selected window',
    },
    {
      label: 'Avg. daily active users',
      value: nf.format(overview.avg_daily_active_users),
      hint: 'Mean distinct humans with ≥1 inbound message per UTC day',
    },
    {
      label: 'Avg. inbound per active user-day',
      value: nf.format(overview.avg_inbound_messages_per_active_user),
      hint: 'Intensity when users show up (user × day)',
    },
    {
      label: 'Avg. messages per conversation',
      value: nf.format(overview.avg_messages_per_conversation),
      hint: 'Inbound + outbound per thread',
    },
  ]

  return (
    <div className="kpi-grid">
      {items.map((item) => (
        <article key={item.label} className="kpi-card">
          <h3 className="kpi-label">{item.label}</h3>
          <p className="kpi-value">{item.value}</p>
          <p className="kpi-hint">{item.hint}</p>
        </article>
      ))}
    </div>
  )
}
